"""empty message

Revision ID: 1f5764b18590
Revises: 
Create Date: 2020-07-14 00:10:31.896616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f5764b18590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'act_tag_assoc', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key(None, 'act_tag_assoc', 'activity', ['activity_id'], ['id'])
    op.create_foreign_key(None, 'activity', 'athlete', ['athlete_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.drop_constraint(None, 'act_tag_assoc', type_='foreignkey')
    op.drop_constraint(None, 'act_tag_assoc', type_='foreignkey')
    # ### end Alembic commands ###
